version: '3.8'

services:

  traffic-violations-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: traffic-violations-api
    image: mespindula/traffic-violations-api
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/traffic_violations_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13
    container_name: db_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: traffic_violations_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: traffic-violations-network
    external: true
